#!/bin/bash
blocks=(" " "▏" "▎" "▍" "▌" "▋" "▊" "▉" "█")
declare -i sleep i j
declare -i seconds rest n
c=""
prev_track=""
COLUMNS=${COLUMNS:-80}  # Default to 80 if COLUMNS is unset
set -e -u -o pipefail
show_countdown=false
channel="fip"
channel_name=""
PARSED=$(getopt -o terjgpmnialfh --long time,electro,rock,jazz,groove,pop,monde,nouveaute,hiphop,reggae,metal,help -- "$@")
if [[ $? -ne 0 ]]; then
	exit 1
fi
eval set -- "$PARSED"
while true; do
	case "$1" in
		-t|--time) show_countdown=true; shift ;;
		-e|--electro) channel="fip_electro"; channel_name="Electro"; shift ;;
		-r|--rock) channel="fip_rock"; channel_name="Rock"; shift ;;
		-j|--jazz) channel="fip_jazz"; channel_name="Jazz"; shift ;;
		-g|--groove) channel="fip_groove"; channel_name="Groove"; shift ;;
		-p|--pop) channel="fip_pop"; channel_name="Pop"; shift ;;
		-m|--monde) channel="fip_world"; channel_name="Monde"; shift ;;
		-n|--nouveaute) channel="fip_nouveautes"; channel_name="Nouveauté"; shift ;;
		-i|--hiphop) channel="fip_hiphop"; channel_name="Hip-Hop"; shift ;;
		-a|--reggae) channel="fip_reggae"; channel_name="Reggae"; shift ;;
		-l|--metal) channel="fip_metal"; channel_name="Metal"; shift ;;
		-f|--sacre-francais) channel="fip_sacre_francais"; channel_name="Sacré Français !"; shift ;;
		-h|--help) echo -e "Display the current playing song on FIP\nfip-now [ -t --time ] [ -h --help ] [ -e --electro ] [ -r --rock ] [ -j --jazz ] [ -g --groove ] [ -p --pop ] [ -m --monde ] [ -n --nouveaute ] [ -i --hiphop ] [ -a --reggae ] [ -l --metal ] [ -f --sacre-francais ]"; exit 0 ;;
		--) shift; break ;;
		*) echo "Invalid option: $1"; exit 1 ;;
	esac
done
clear_eol=$(tput el)
cursor_up=$(tput cuu1)
titlecolor=$(tput bold)$(tput setaf 1)
labelcolor=$(tput setaf 2)
artistcolor=$(tput bold)$(tput setaf 4)
reset=$(tput op)$(tput sgr0)
while [[ "$c" != "q" ]]; do
	data=$(curl -f -s "https://www.radiofrance.fr/fip/api/live?webradio=$channel")
	if [ $? != 0 ]; then
		title="(Download error)"
		artist=
		year=
		album=
		sleep=5
	else
		title=$(echo "$data" | jq -r '.now.firstLine.title')
		artist=$(echo "$data" | jq -r '.now.secondLine.title')
		year=$(echo "$data" | jq -r '.now.song.year')
		album=$(echo "$data" | jq -r '.now.song.release.title')
		image=$(echo "$data" | jq -r '.now.visuals.card.src')
		delayToRefresh=$(echo "$data" | jq -r '.delayToRefresh')
		sleep=$(dc <<<"$delayToRefresh 1000/p")
	fi
	track="$artist - $title"
	formatted_album="${album// /-}"
	if [[ "$track" != "$prev_track" ]]; then
		notify-send "🎵 Now Playing on FIP $channel_name" "$track"
		prev_track="$track"
	fi
	wget -qO ~/.fip/$formatted_album.webp $image/288x288
	magick ~/.fip/$formatted_album.webp ~/.fip/$formatted_album.jpg && rm ~/.fip/$formatted_album.webp
	title=${title:0:$((COLUMNS - 10))}
	artist=${artist:0:$((COLUMNS - 10))}
	album=${album:0:$((COLUMNS - 10))}
	year=${year:0:$((COLUMNS - 10))}
	echo "  ${labelcolor}Title:$reset  $titlecolor$title$reset$clear_eol"
	echo " ${labelcolor}Artist:$reset  $artistcolor$artist$reset$clear_eol"
	echo "  ${labelcolor}Album:$reset  $album$clear_eol"
	echo "   ${labelcolor}Year:$reset  $year$clear_eol"
	feh ~/.fip/$formatted_album.jpg &
	seconds=10#$sleep
	((seconds += SECONDS + 2))
	while ((SECONDS < seconds)) && [[ "$c" != "q" ]]; do
		if $show_countdown; then
			((n = seconds / 8))
			((rest = seconds % 8))
			if ((n >= COLUMNS)); then ((n = COLUMNS - 1)); ((rest = 8)); fi
			printf "%*d:%02d\r" $((COLUMNS - 3)) $((seconds / 60)) $((seconds % 60))
			while ((n > 0)); do echo -n "█"; ((n--)); done
			echo -e "${blocks[$rest]}\r\c"
		fi
		read -n 1 -t 1 -s c || true
	done
	if [[ "$c" != "q" ]]; then
		echo -n "$cursor_up$cursor_up$cursor_up$cursor_up"
	fi
done
echo
